[build]
  publish = "dist"
  command = "npm install && npm run build"

[[redirects]]
  from = "/privacy-policy"
  to = "/privacy"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

# Form settings
[[form]]
  name = "ai-assessment-admin"
  [form.settings]
    [form.settings.notification]
      recipients = ["sarafollador01@gmail.com"]
      subject = "New AI Assessment Completed - Pro-Actis"

[[form]]
  name = "ai-assessment-user"
  [form.settings]
    [form.settings.notification]
      recipients = ["sarafollador01@gmail.com"]
      subject = "AI Assessment Results Sent to User - Pro-Actis"

[[form]]
  name = "demo-request"
  [form.settings]
    [form.settings.notification]
      recipients = ["sarafollador01@gmail.com"]
      subject = "New Demo Request from Pro-Actis"

[[form]]
  name = "info-request"
  [form.settings]
    [form.settings.notification]
      recipients = ["sarafollador01@gmail.com"]
      subject = "New Info Request from Pro-Actis"

[[form]]
  name = "newsletter-subscription"
  [form.settings]
    [form.settings.notification]
      recipients = ["sarafollador01@gmail.com"]
      subject = "New Newsletter Subscription from Pro-Actis"

[[form]]
  name = "audio-upload"
  [form.settings]
    [form.settings.notification]
      recipients = ["sarafollador01@gmail.com"]
      subject = "New Audio Content Upload from Pro-Actis"

[[form]]
  name = "content-ideas-email"
  [form.settings]
    [form.settings.notification]
      recipients = ["sarafollador01@gmail.com"]
      subject = "New Content Ideas Request from Pro-Actis"

[[form]]
  name = "linkedin-posts-email"
  [form.settings]
    [form.settings.notification]
      recipients = ["sarafollador01@gmail.com"]
      subject = "New LinkedIn Posts Request from Pro-Actis"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://www.google-analytics.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://www.google-analytics.com; frame-src 'self' https://www.youtube.com https://www.youtube-nocookie.com"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
