import { QuizResult, getQualificationMessage } from "./quizScoring";

export interface EmailData {
  userEmail: string;
  firstName: string;
  lastName: string;
  firmName: string;
  result: QuizResult;
  completedAt: Date;
}

// Create a rich text format that works well in email clients
export const generateEmailMessage = (
  data: EmailData,
  isForAdmin: boolean = false,
): string => {
  const qualificationInfo = getQualificationMessage(data.result.qualification);

  if (isForAdmin) {
    return `🚨 NEW AI ASSESSMENT COMPLETED 🚨

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

👤 CLIENT INFORMATION:
Name: ${data.firstName} ${data.lastName}
Email: ${data.userEmail}
Firm: ${data.firmName}
Completed: ${data.completedAt.toLocaleDateString()} at ${data.completedAt.toLocaleTimeString()}

🎯 LEAD QUALIFICATION: ${data.result.qualification.toUpperCase()} PRIORITY

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📊 ASSESSMENT RESULTS:

🔥 OVERALL AI READINESS SCORE: ${data.result.overallScore}%

📈 CATEGORY BREAKDOWN:
👥 Client AI Expectations: ${data.result.categoryScores.client_ai}%
⚡ Current AI Implementation: ${data.result.categoryScores.personal_ai}%
🎯 AI Readiness Level: ${data.result.categoryScores.readiness}%

💡 SUMMARY:
${qualificationInfo.message}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🚀 STRATEGIC RECOMMENDATIONS:

${data.result.recommendations.map((rec, i) => `${i + 1}. ${rec}`).join("\n\n")}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📞 IMMEDIATE ACTIONS REQUIRED:

${
  data.result.qualification === "high"
    ? `🔴 HIGH PRIORITY LEAD - Contact immediately!
📧 Email: ${data.userEmail}
📞 Schedule consultation call ASAP
🎯 Strong potential for immediate conversion`
    : data.result.qualification === "medium"
      ? `🟡 MEDIUM PRIORITY LEAD - Follow up within 48 hours
📧 Email: ${data.userEmail}
📞 Schedule optimization strategy discussion
🎯 Good potential with proper nurturing`
      : `🟢 LOW PRIORITY LEAD - Add to nurturing sequence
📧 Email: ${data.userEmail}
📞 Schedule discovery call when appropriate
🎯 Long-term potential with education`
}

REPLY TO: ${data.userEmail}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Generated by Pro-Actis AI Assessment System
${data.completedAt.toLocaleString()}`;
  } else {
    return `🎉 YOUR AI READINESS ASSESSMENT RESULTS 🎉

Hello ${data.firstName}!

Thank you for completing the Pro-Actis AI Readiness Assessment. Your results are ready!

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🔥 YOUR OVERALL AI READINESS SCORE: ${data.result.overallScore}%

🏆 QUALIFICATION LEVEL: ${data.result.qualification.toUpperCase()} PRIORITY

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📊 DETAILED BREAKDOWN:

👥 CLIENT AI EXPECTATIONS: ${data.result.categoryScores.client_ai}%
   How your clients view and expect AI usage in legal services

⚡ CURRENT AI IMPLEMENTATION: ${data.result.categoryScores.personal_ai}%
   Your firm's current adoption and usage of AI tools

🎯 AI READINESS INFRASTRUCTURE: ${data.result.categoryScores.readiness}%
   Your team and technology preparedness for AI integration

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

💡 WHAT THIS MEANS FOR YOU:

${qualificationInfo.message}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

${
  data.result.strengths.length > 0
    ? `🎯 YOUR KEY STRENGTHS:

${data.result.strengths.map((strength) => `✅ ${strength}`).join("\n")}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

`
    : ""
}

${
  data.result.improvements.length > 0
    ? `📈 AREAS FOR IMPROVEMENT:

${data.result.improvements.map((improvement) => `🔧 ${improvement}`).join("\n")}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

`
    : ""
}

🚀 STRATEGIC RECOMMENDATIONS FOR YOUR FIRM:

${data.result.recommendations.map((rec, i) => `${i + 1}. ${rec}`).join("\n\n")}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🎯 READY TO ACCELERATE YOUR AI JOURNEY?

Based on your assessment results, Pro-Actis can help you implement the right AI strategy to meet your clients' expectations and gain competitive advantage.

📞 BOOK YOUR FREE 30-MINUTE DISCOVERY CALL:
https://calendly.com/mylinkedinads/talking-about-your-a-i-strategy

During this call, we'll:
✅ Review your specific assessment results in detail
✅ Identify immediate opportunities for AI implementation
✅ Create a customized roadmap for your firm
✅ Discuss how to leverage AI for competitive advantage

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Pro-Actis AI - Empowering Legal Excellence Through Artificial Intelligence

🌐 Website: www.pro-actis.com
📧 Email: contact@pro-actis.com

Generated on ${data.completedAt.toLocaleDateString()}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

This email was sent because you completed an AI readiness assessment on our website. If you have any questions about your results or Pro-Actis services, please contact us at the email above.`;
  }
};
